/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그인
         * @description 이메일·비밀번호를 검증하고 Access 토큰을 받는다.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 토큰 재발급
         * @description Refresh 토큰으로 Access·Refresh 토큰을 다시 받는다. 회전 방식이라 이전 Refresh 토큰은 무효가 된다.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 가입
         * @description 이메일·비밀번호로 가입하고 즉시 Access 토큰을 받는다.
         */
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contracts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 계약 열람
         * @description 조항 전문·서명 시각·무결성 해시를 돌려준다. 분쟁 시 소명 자료 경로다. 당사자에게만 열린다.
         */
        get: operations["getContract"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contracts/{id}/sign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 전자 서명
         * @description 로그인 사용자가 해당 계약의 당사자인지 확인한 뒤 서명 시각을 기록한다. 양측이 모두 서명하면 계약은 SIGNED, 예약 요청은 CONTRACT_SIGNED가 된다. 당사자가 아니면 403, 이미 서명했으면 409다.
         */
        post: operations["signContract"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/door-events/{eventId}/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * MQTT 발행 결과 보고
         * @description 모바일이 실제로 발행했는지를 보고해 이벤트를 DELIVERED 또는 FAILED로 마감한다. 이 단계가 있어야 승인 기록이 전송 기록이 된다. 개방을 요청한 본인만 마감할 수 있다.
         */
        post: operations["ackDoorEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fixtures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 집기 라이브러리 조회
         * @description category를 주면 해당 분류만, 없으면 전체를 돌려준다.
         */
        get: operations["listFixtures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reservation-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 예약 목록
         * @description 로그인한 사용자가 만든 예약 요청을 최근 순으로 돌려준다. status를 주면 그 상태만 거른다. 건물주의 '내 공간 예약 목록'은 조회 축이 다른 별개의 유스케이스이며 이 경로가 아니다.
         */
        get: operations["listReservationRequests"];
        put?: never;
        /**
         * 예약 요청 생성
         * @description 빌더가 만든 도면을 서버에서 재검증하고 견적과 함께 예약 요청을 만든다. 그리드 범위를 벗어나거나 집기가 겹치면 400이고, 같은 공간에 기간이 겹치는 결제 완료 예약이 있으면 409다. 409는 조기 안내이며 자리를 확정하지 않는다 — 최종 판정은 결제 승인이 분산 락 안에서 한다.
         */
        post: operations["createReservationRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reservation-requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 예약 요청 단건 조회
         * @description 견적 스냅샷을 포함한 예약 요청을 돌려준다. 예약의 브랜드 본인이거나 그 공간의 건물주만 볼 수 있다.
         */
        get: operations["getReservationRequest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reservation-requests/{id}/contract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 예약 요청의 계약 조회
         * @description 예약 요청에 딸린 계약을 가져온다. 아직 없으면 404다. 빌더에서 계약 단계로 재진입할 때(새로고침·서명 링크 재방문) 계약 ID를 모르는 채로 기존 계약을 되찾기 위한 경로다. 당사자에게만 열린다.
         */
        get: operations["getContractByReservation"];
        put?: never;
        /**
         * 계약서 생성
         * @description 예약 요청 데이터를 표준 템플릿에 바인딩해 조항 전문을 스냅샷으로 저장한다. 예약 요청 상태는 CONTRACT_PENDING으로 전이된다. 예약 하나에 계약은 하나이며, 이미 있으면 409다 — 그때는 조회 API로 기존 계약을 가져간다. 브랜드·건물주 당사자만 부를 수 있으며 그 외에는 403이다.
         */
        post: operations["createContract"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reservation-requests/{id}/door-open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 도어 오픈 권한 검증·기록
         * @description 예약 당사자인지와 시간창(시작 10분 전 ~ 종료) 안인지를 서버가 판정하고, 통과하면 발행할 MQTT 토픽과 페이로드를 내려준다. 판정 권위는 서버이며 클라이언트 시계를 보지 않는다.
         */
        post: operations["openDoor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reservation-requests/{id}/payment/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 결제 승인
         * @description 분산 락 안에서 예약 상태·기간 겹침·집기 가용량·전력 한도·금액을 재확인한 뒤 PG 승인을 호출하고, 예약을 PAID로 확정하며 분할 정산 Row를 만든다. 요청 금액은 승인 금액이 아니라 대조 대상이다.
         */
        post: operations["confirmPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reservation-requests/{id}/payment/prepare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 결제 준비
         * @description 토스 결제 위젯에 넘길 주문 정보를 발급한다. 락을 잡지 않으며 자리를 선점하지 않는다. orderId는 호출마다 새로 발급되고 재사용하지 않는다.
         */
        post: operations["preparePayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settlements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 분할 정산 내역 조회
         * @description 결제 1건이 만든 분할 정산 Row를 모두 돌려준다. 보증금 Row는 ESCROW_HELD 상태이며 정산이 아니라 반환 대상이다.
         */
        get: operations["listSettlements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 반경 공실 검색
         * @description 중심 좌표 기준 반경(m) 안의 ACTIVE 공간을 찾는다. 면적·대여료·전력 필터는 모두 선택이다.
         */
        get: operations["searchSpaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spaces/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 상가 상세
         * @description 요약 카드 필드에 빌더 캔버스용 grid 정보를 더해 돌려준다.
         */
        get: operations["getSpace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spaces/{spaceId}/fixture-availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 날짜별 집기 가용 수량
         * @description 해당 기간에 배치 가능한 집기 수량을 집기별로 돌려준다. 수량은 질의 기간 중 가장 많이 잡힌 날 기준이며, 다른 공간의 예약이 잡아간 수량도 함께 차감된다.
         */
        get: operations["getFixtureAvailability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 에러 상세. 성공 응답에서는 null이다. */
        ApiError: {
            /**
             * @description 에러 코드 상수. 클라이언트는 이 값으로 분기한다
             * @example VALIDATION_FAILED
             * @enum {string}
             */
            code: "VALIDATION_FAILED" | "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "METHOD_NOT_ALLOWED" | "UNSUPPORTED_MEDIA_TYPE" | "INTERNAL_ERROR" | "EMAIL_ALREADY_EXISTS" | "INVALID_CREDENTIALS" | "SPACE_NOT_FOUND" | "FIXTURE_NOT_FOUND" | "RESERVATION_REQUEST_NOT_FOUND" | "LAYOUT_OUT_OF_BOUNDS" | "LAYOUT_OVERLAP" | "FIXTURE_STOCK_EXCEEDED" | "FIXTURE_UNAVAILABLE" | "SPACE_ALREADY_BOOKED" | "POWER_LIMIT_EXCEEDED" | "CONTRACT_NOT_FOUND" | "NOT_CONTRACT_PARTY" | "CONTRACT_ALREADY_EXISTS" | "CONTRACT_ALREADY_SIGNED" | "CONTRACT_INTEGRITY_VIOLATION" | "REFRESH_TOKEN_INVALID" | "PAYMENT_ALREADY_COMPLETED" | "ORDER_ID_ALREADY_USED" | "PAYMENT_RESULT_UNKNOWN" | "PAYMENT_DECLINED" | "PAYMENT_AMOUNT_MISMATCH" | "LOCK_ACQUISITION_FAILED" | "DOOR_NOT_YET_OPENABLE" | "RESERVATION_NOT_PAID" | "DOOR_EVENT_ALREADY_ACKED";
            /**
             * @description 사람이 읽는 설명. 분기 조건으로 쓰지 말 것
             * @example email은 필수입니다
             */
            message: string;
        };
        /** @description 실패 응답 봉투. data는 항상 null이고 error에 코드·메시지가 담긴다. */
        ApiErrorResponse: {
            /** @description 실패 시 항상 null */
            data: unknown;
            error: components["schemas"]["ApiError"];
        };
        /** @description 공통 응답 봉투 */
        ApiResponseAuthResponse: {
            /** @description 성공 시 페이로드. 실패 시 null */
            data: components["schemas"]["AuthResponse"] | null;
            /** @description 실패 시 에러 상세. 성공 시 null */
            error: components["schemas"]["ApiError"] | null;
        };
        /** @description 공통 응답 봉투 */
        ApiResponseContractResponse: {
            /** @description 성공 시 페이로드. 실패 시 null */
            data: components["schemas"]["ContractResponse"] | null;
            /** @description 실패 시 에러 상세. 성공 시 null */
            error: components["schemas"]["ApiError"] | null;
        };
        /** @description 공통 응답 봉투 */
        ApiResponseDoorAckResponse: {
            /** @description 성공 시 페이로드. 실패 시 null */
            data: components["schemas"]["DoorAckResponse"] | null;
            /** @description 실패 시 에러 상세. 성공 시 null */
            error: components["schemas"]["ApiError"] | null;
        };
        /** @description 공통 응답 봉투 */
        ApiResponseDoorOpenResponse: {
            /** @description 성공 시 페이로드. 실패 시 null */
            data: components["schemas"]["DoorOpenResponse"] | null;
            /** @description 실패 시 에러 상세. 성공 시 null */
            error: components["schemas"]["ApiError"] | null;
        };
        /** @description 공통 응답 봉투 */
        ApiResponseListFixtureAvailabilityResponse: {
            /** @description 성공 시 페이로드. 실패 시 null */
            data: components["schemas"]["FixtureAvailabilityResponse"][] | null;
            /** @description 실패 시 에러 상세. 성공 시 null */
            error: components["schemas"]["ApiError"] | null;
        };
        /** @description 공통 응답 봉투 */
        ApiResponseListFixtureResponse: {
            /** @description 성공 시 페이로드. 실패 시 null */
            data: components["schemas"]["FixtureResponse"][] | null;
            /** @description 실패 시 에러 상세. 성공 시 null */
            error: components["schemas"]["ApiError"] | null;
        };
        /** @description 공통 응답 봉투 */
        ApiResponseListReservationRequestResponse: {
            /** @description 성공 시 페이로드. 실패 시 null */
            data: components["schemas"]["ReservationRequestResponse"][] | null;
            /** @description 실패 시 에러 상세. 성공 시 null */
            error: components["schemas"]["ApiError"] | null;
        };
        /** @description 공통 응답 봉투 */
        ApiResponseListSettlementResponse: {
            /** @description 성공 시 페이로드. 실패 시 null */
            data: components["schemas"]["SettlementResponse"][] | null;
            /** @description 실패 시 에러 상세. 성공 시 null */
            error: components["schemas"]["ApiError"] | null;
        };
        /** @description 공통 응답 봉투 */
        ApiResponseListSpaceSummaryResponse: {
            /** @description 성공 시 페이로드. 실패 시 null */
            data: components["schemas"]["SpaceSummaryResponse"][] | null;
            /** @description 실패 시 에러 상세. 성공 시 null */
            error: components["schemas"]["ApiError"] | null;
        };
        /** @description 공통 응답 봉투 */
        ApiResponsePaymentConfirmResponse: {
            /** @description 성공 시 페이로드. 실패 시 null */
            data: components["schemas"]["PaymentConfirmResponse"] | null;
            /** @description 실패 시 에러 상세. 성공 시 null */
            error: components["schemas"]["ApiError"] | null;
        };
        /** @description 공통 응답 봉투 */
        ApiResponsePaymentPrepareResponse: {
            /** @description 성공 시 페이로드. 실패 시 null */
            data: components["schemas"]["PaymentPrepareResponse"] | null;
            /** @description 실패 시 에러 상세. 성공 시 null */
            error: components["schemas"]["ApiError"] | null;
        };
        /** @description 공통 응답 봉투 */
        ApiResponseReservationRequestResponse: {
            /** @description 성공 시 페이로드. 실패 시 null */
            data: components["schemas"]["ReservationRequestResponse"] | null;
            /** @description 실패 시 에러 상세. 성공 시 null */
            error: components["schemas"]["ApiError"] | null;
        };
        /** @description 공통 응답 봉투 */
        ApiResponseSpaceDetailResponse: {
            /** @description 성공 시 페이로드. 실패 시 null */
            data: components["schemas"]["SpaceDetailResponse"] | null;
            /** @description 실패 시 에러 상세. 성공 시 null */
            error: components["schemas"]["ApiError"] | null;
        };
        /** @description 공통 응답 봉투 */
        ApiResponseTokenPairResponse: {
            /** @description 성공 시 페이로드. 실패 시 null */
            data: components["schemas"]["TokenPairResponse"] | null;
            /** @description 실패 시 에러 상세. 성공 시 null */
            error: components["schemas"]["ApiError"] | null;
        };
        /** @description 인증 결과 */
        AuthResponse: {
            /** @description JWT Access 토큰. 이후 요청에 Bearer로 싣는다 */
            accessToken: string;
            /** @description Refresh 토큰. 만료 시 /auth/refresh로 재발급받는다 */
            refreshToken: string;
            /** @description 인증된 사용자 정보 */
            user: components["schemas"]["UserSummary"];
        };
        /** @description 계약 조항 */
        ClauseDto: {
            /**
             * @description 조항 전문
             * @example 본 계약은 팝업스토어 단기 운영을 목적으로 한다.
             */
            body: string;
            /**
             * @description 조항 제목
             * @example 제1조 (목적)
             */
            title: string;
        };
        /** @description 계약 */
        ContractResponse: {
            /**
             * Format: date-time
             * @description 브랜드 서명 시각(UTC). 미서명이면 null
             * @example 2026-08-22T05:12:31Z
             */
            brandSignedAt: string | null;
            /** @description 생성 시점의 조항 전문 스냅샷 */
            clauses: components["schemas"]["ClauseDto"][];
            /**
             * @description 조항 전문+타임스탬프의 SHA-256 무결성 해시
             * @example 3f2b7c1d9a4e5f60718293a4b5c6d7e8f90a1b2c3d4e5f60718293a4b5c6d7e8
             */
            contentHash: string;
            /**
             * Format: int64
             * @description 계약 ID
             * @example 1
             */
            id: number;
            /**
             * Format: date-time
             * @description 건물주 서명 시각(UTC). 미서명이면 null
             * @example 2026-08-22T06:40:02Z
             */
            landlordSignedAt: string | null;
            /**
             * Format: int64
             * @description 대상 예약 요청 ID
             * @example 1
             */
            reservationRequestId: number;
            /**
             * @description 계약 상태
             * @enum {string}
             */
            status: "PENDING" | "SIGNED";
            /**
             * @description 템플릿 버전
             * @example v1
             */
            templateVersion: string;
            /**
             * @description 계약 명칭. 일시사용 임대차 요건 보존을 위해 고정된 값이다
             * @example 단기 공간사용 제휴계약
             */
            title: string;
        };
        /** @description 예약 요청 생성 */
        CreateReservationRequest: {
            /**
             * Format: date
             * @description 사용 종료일(yyyy-MM-dd)
             * @example 2026-09-14
             */
            endDate: string;
            /** @description 빌더가 만든 도면 */
            layout: components["schemas"]["LayoutDto"];
            /**
             * Format: int64
             * @description 대상 공간 ID
             * @example 1
             */
            spaceId: number;
            /**
             * Format: date
             * @description 사용 시작일(yyyy-MM-dd)
             * @example 2026-09-01
             */
            startDate: string;
        };
        /** @description MQTT 발행 결과 보고 */
        DoorAckRequest: {
            /**
             * @description 발행 성공 여부
             * @example true
             */
            success: boolean;
        };
        /** @description 도어 이벤트 마감 결과 */
        DoorAckResponse: {
            /**
             * Format: date-time
             * @description 보고 접수 시각(UTC)
             */
            ackedAt: string;
            /**
             * Format: int64
             * @description 도어 이벤트 ID
             * @example 123
             */
            eventId: number;
            /**
             * @description 마감 상태 — DELIVERED 또는 FAILED
             * @enum {string}
             */
            status: "AUTHORIZED" | "DELIVERED" | "FAILED";
        };
        /** @description MQTT 발행 페이로드 */
        DoorCommandPayload: {
            /**
             * @description 명령
             * @example OPEN
             */
            action: string;
            /**
             * Format: int64
             * @description 도어 이벤트 ID
             * @example 123
             */
            eventId: number;
            /**
             * Format: date-time
             * @description 발급 시각(UTC)
             */
            issuedAt: string;
            /**
             * Format: int64
             * @description 예약 요청 ID
             * @example 45
             */
            reservationId: number;
        };
        /** @description 도어 오픈 승인 결과 */
        DoorOpenResponse: {
            /**
             * Format: int64
             * @description 도어 이벤트 ID. ack에 이 값을 쓴다
             * @example 123
             */
            eventId: number;
            /** @description 발행할 페이로드. 그대로 발행한다 */
            payload: components["schemas"]["DoorCommandPayload"];
            /**
             * @description 이벤트 상태. 승인 직후는 항상 AUTHORIZED다
             * @enum {string}
             */
            status: "AUTHORIZED" | "DELIVERED" | "FAILED";
            /**
             * @description 상태 구독 토픽. 구독 실패는 개방 흐름을 막지 않는다(UI 편의일 뿐 개방의 필요조건이 아니다)
             * @example popupready/locks/1/status
             */
            statusTopic: string;
            /**
             * @description 발행할 MQTT 토픽
             * @example popupready/locks/1/command
             */
            topic: string;
        };
        /** @description 견적 내역 */
        EstimateResponse: {
            /**
             * Format: int32
             * @description 대여 일수
             * @example 14
             */
            days: number;
            /**
             * Format: int64
             * @description 보증금(원). 일시사용 요건상 하향 설계된다
             * @example 630000
             */
            deposit: number;
            /**
             * Format: int64
             * @description 집기 렌털료 합계(원)
             * @example 420000
             */
            fixtureRentalTotal: number;
            /**
             * Format: int64
             * @description 공간 대여료 합계(원)
             * @example 6300000
             */
            spaceRentTotal: number;
            /**
             * Format: int64
             * @description 총 견적(원)
             * @example 7350000
             */
            totalAmount: number;
        };
        /** @description 날짜별 집기 가용 수량 */
        FixtureAvailabilityResponse: {
            /**
             * Format: int32
             * @description 배치 가능 수량 (totalStock - reservedQty)
             * @example 7
             */
            availableQty: number;
            /**
             * Format: int64
             * @description 집기 ID
             * @example 1
             */
            fixtureId: number;
            /**
             * Format: int32
             * @description 질의 기간 중 가장 많이 잡힌 날의 예약 수량
             * @example 3
             */
            reservedQty: number;
            /**
             * Format: int32
             * @description 총 보유 수량
             * @example 10
             */
            totalStock: number;
        };
        /** @description 모듈러 집기 */
        FixtureResponse: {
            /**
             * @description 분류
             * @enum {string}
             */
            category: "HANGER" | "POS" | "SHOWCASE" | "LIGHTING" | "SHELF" | "ETC";
            /**
             * Format: int64
             * @description 일일 렌털료(원)
             * @example 12000
             */
            dailyRentalFee: number;
            /**
             * Format: int32
             * @description 세로 규격(mm)
             * @example 500
             */
            depthMm: number;
            /**
             * Format: int64
             * @description 집기 ID
             * @example 1
             */
            id: number;
            /**
             * @description 집기 이름
             * @example 스탠드 행거 1200
             */
            name: string;
            /**
             * Format: int32
             * @description 소비 전력(W). 비전기 집기는 0
             * @example 0
             */
            powerWatt: number;
            /**
             * Format: int32
             * @description 총 재고 수량
             * @example 40
             */
            stockQty: number;
            /**
             * Format: int32
             * @description 가로 규격(mm)
             * @example 1200
             */
            widthMm: number;
        };
        /** @description 2D 도면 레이아웃 */
        LayoutDto: {
            /**
             * Format: int32
             * @description 그리드 한 칸의 실제 크기(mm)
             * @example 500
             */
            cellSizeMm: number;
            /**
             * Format: int32
             * @description 그리드 가로 칸 수
             * @example 20
             */
            gridCols: number;
            /**
             * Format: int32
             * @description 그리드 세로 칸 수
             * @example 12
             */
            gridRows: number;
            /** @description 배치된 집기 목록. 빈 배열도 허용한다 */
            items: components["schemas"]["LayoutItemDto"][];
        };
        /** @description 배치된 집기 */
        LayoutItemDto: {
            /**
             * Format: int32
             * @description 좌상단 기준 열 좌표(0-base)
             * @example 4
             */
            col: number;
            /**
             * Format: int64
             * @description 집기 ID
             * @example 3
             */
            fixtureId: number;
            /**
             * Format: int32
             * @description 회전각. 0 | 90 | 180 | 270 중 하나여야 한다
             * @example 90
             */
            rotation: number;
            /**
             * Format: int32
             * @description 좌상단 기준 행 좌표(0-base)
             * @example 2
             */
            row: number;
        };
        /** @description 위경도 좌표(WGS84) */
        LocationDto: {
            /**
             * Format: double
             * @description 위도
             * @example 37.5445
             */
            lat: number;
            /**
             * Format: double
             * @description 경도
             * @example 127.0557
             */
            lng: number;
        };
        /** @description 로그인 요청 */
        LoginRequest: {
            /**
             * @description 이메일(로그인 ID)
             * @example brand@popupready.com
             */
            email: string;
            /**
             * @description 비밀번호
             * @example password123
             */
            password: string;
        };
        /** @description 결제 승인 요청 */
        PaymentConfirmRequest: {
            /**
             * Format: int64
             * @description 클라이언트가 본 금액(원). 서버 견적과 대조만 한다
             * @example 6930000
             */
            amount?: number;
            /** @description 결제 준비 때 받은 주문 ID */
            orderId: string;
            /** @description 토스가 발급한 결제 키 */
            paymentKey: string;
        };
        /** @description 결제 승인 결과 */
        PaymentConfirmResponse: {
            /**
             * Format: int64
             * @description 승인된 금액(원)
             * @example 6930000
             */
            amount: number;
            /**
             * Format: date-time
             * @description PG 승인 시각(UTC)
             */
            approvedAt: string;
            /** @description 토스 주문 ID */
            orderId: string;
            /**
             * Format: int64
             * @description 예약 요청 ID
             * @example 1
             */
            reservationRequestId: number;
            /**
             * @description 확정된 예약 상태
             * @enum {string}
             */
            reservationStatus: "DRAFT" | "CONTRACT_PENDING" | "CONTRACT_SIGNED" | "PAYMENT_PENDING" | "PAID" | "CANCELLED";
            /** @description 이 결제가 만든 분할 정산 Row */
            settlements: components["schemas"]["SettlementResponse"][];
            /**
             * @description 결제 상태
             * @enum {string}
             */
            status: "READY" | "PAID" | "FAILED" | "CANCELLED" | "UNKNOWN";
        };
        /** @description 결제 준비 결과 */
        PaymentPrepareResponse: {
            /**
             * Format: int64
             * @description 결제할 금액(원). 견적 스냅샷의 합계다
             * @example 6930000
             */
            amount: number;
            /** @description 토스 주문 ID. 호출마다 새로 발급되며 재사용하지 않는다 */
            orderId: string;
            /**
             * @description 위젯에 표시할 주문명
             * @example 성수 팝업 스페이스 14일 대여
             */
            orderName: string;
        };
        /** @description 토큰 재발급 요청 */
        RefreshRequest: {
            /** @description 발급받은 Refresh 토큰 */
            refreshToken: string;
        };
        /** @description 예약 요청 */
        ReservationRequestResponse: {
            /**
             * Format: int64
             * @description 요청한 브랜드 사용자 ID
             * @example 1
             */
            brandUserId: number;
            /**
             * Format: date
             * @description 사용 종료일
             * @example 2026-09-14
             */
            endDate: string;
            /** @description 견적 내역 */
            estimate: components["schemas"]["EstimateResponse"];
            /**
             * Format: int64
             * @description 예약 요청 ID
             * @example 1
             */
            id: number;
            /** @description 서버가 재검증한 도면. 요청한 내용이 그대로 되돌아온다 */
            layout: components["schemas"]["LayoutDto"];
            /**
             * Format: int64
             * @description 대상 공간 ID
             * @example 1
             */
            spaceId: number;
            /**
             * Format: date
             * @description 사용 시작일
             * @example 2026-09-01
             */
            startDate: string;
            /**
             * @description 예약 요청 상태
             * @enum {string}
             */
            status: "DRAFT" | "CONTRACT_PENDING" | "CONTRACT_SIGNED" | "PAYMENT_PENDING" | "PAID" | "CANCELLED";
        };
        /** @description 분할 정산 Row */
        SettlementResponse: {
            /**
             * Format: int64
             * @description 원천 차감된 플랫폼 수수료(원)
             * @example 630000
             */
            feeAmount: number;
            /**
             * Format: int64
             * @description 정산 대상 총액(원)
             * @example 6300000
             */
            grossAmount: number;
            /**
             * Format: int64
             * @description 실제로 이체할 금액(원)
             * @example 5670000
             */
            netAmount: number;
            /**
             * Format: int64
             * @description 정산 대상 사용자 ID
             * @example 2
             */
            payeeId: number;
            /**
             * @description 정산 상태. 보증금만 ESCROW_HELD로 생성된다
             * @enum {string}
             */
            status: "PENDING" | "ESCROW_HELD" | "APPROVED" | "TRANSFERRED";
            /**
             * @description 정산 종류
             * @enum {string}
             */
            type: "SPACE_RENT" | "FIXTURE_RENTAL" | "DEPOSIT" | "PLATFORM_FEE";
        };
        /** @description 가입 요청 */
        SignupRequest: {
            /**
             * Format: email
             * @description 이메일(로그인 ID)
             * @example brand@popupready.com
             */
            email: string;
            /**
             * @description 표시 이름
             * @example 김브랜드
             */
            name: string;
            /**
             * @description 비밀번호(8자 이상)
             * @example password123
             */
            password: string;
            /**
             * @description 역할
             * @enum {string}
             */
            role: "BRAND" | "LANDLORD" | "VENDOR" | "ADMIN";
        };
        /** @description 공간 상세(빌더 진입용) */
        SpaceDetailResponse: {
            /**
             * @description 주소
             * @example 서울 성동구 연무장길 45
             */
            address: string;
            /**
             * Format: int32
             * @description 그리드 한 칸의 실제 크기(mm)
             * @example 500
             */
            cellSizeMm: number;
            /**
             * Format: int64
             * @description 일일 대여료(원)
             * @example 450000
             */
            dailyRent: number;
            /**
             * @description 보증금 비율. 일시사용 요건상 하향 설계된다
             * @example 0.1
             */
            depositRate: number;
            /**
             * Format: double
             * @description 실면적(㎡)
             * @example 82.5
             */
            floorAreaM2: number;
            /**
             * Format: int32
             * @description 도면 그리드 가로 칸 수
             * @example 20
             */
            gridCols: number;
            /**
             * Format: int32
             * @description 도면 그리드 세로 칸 수
             * @example 12
             */
            gridRows: number;
            /**
             * Format: int64
             * @description 공간 ID
             * @example 1
             */
            id: number;
            /** @description 위치 좌표 */
            location: components["schemas"]["LocationDto"];
            /**
             * Format: int32
             * @description 허용 전력(W). 배치한 집기 소비전력 합이 이 값을 넘으면 결제가 차단된다
             * @example 5000
             */
            maxPowerWatt: number;
            /**
             * @description 공간 이름
             * @example 성수 연무장길 팝업 1층
             */
            name: string;
            /**
             * @description 공간 상태
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE";
        };
        /** @description 공간 요약(지도 마커·요약 카드용) */
        SpaceSummaryResponse: {
            /**
             * @description 주소
             * @example 서울 성동구 연무장길 45
             */
            address: string;
            /**
             * Format: int64
             * @description 일일 대여료(원)
             * @example 450000
             */
            dailyRent: number;
            /**
             * Format: double
             * @description 실면적(㎡)
             * @example 82.5
             */
            floorAreaM2: number;
            /**
             * Format: int64
             * @description 공간 ID
             * @example 1
             */
            id: number;
            /** @description 위치 좌표 */
            location: components["schemas"]["LocationDto"];
            /**
             * Format: int32
             * @description 허용 전력(W)
             * @example 5000
             */
            maxPowerWatt: number;
            /**
             * @description 공간 이름
             * @example 성수 연무장길 팝업 1층
             */
            name: string;
        };
        /** @description 토큰 재발급 결과 */
        TokenPairResponse: {
            /** @description 새 JWT Access 토큰 */
            accessToken: string;
            /** @description 새 Refresh 토큰. 이전 것은 무효가 된다 */
            refreshToken: string;
        };
        /** @description 로그인한 사용자 요약 */
        UserSummary: {
            /**
             * @description 이메일(로그인 ID)
             * @example brand@popupready.com
             */
            email: string;
            /**
             * Format: int64
             * @description 사용자 ID
             * @example 1
             */
            id: number;
            /**
             * @description 표시 이름
             * @example 김브랜드
             */
            name: string;
            /**
             * @description 역할
             * @enum {string}
             */
            role: "BRAND" | "LANDLORD" | "VENDOR" | "ADMIN";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 로그인 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseAuthResponse"];
                };
            };
            /** @description 요청 값 검증 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 이메일 또는 비밀번호 불일치 (INVALID_CREDENTIALS) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 지원하지 않는 Content-Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseTokenPairResponse"];
                };
            };
            /** @description 요청 값 검증 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 만료·위조·재사용된 토큰 (REFRESH_TOKEN_INVALID) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 지원하지 않는 Content-Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseAuthResponse"];
                };
            };
            /** @description 요청 값 검증 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 이미 사용 중인 이메일 (EMAIL_ALREADY_EXISTS) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 지원하지 않는 Content-Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    getContract: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 계약 ID
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseContractResponse"];
                };
            };
            /** @description 요청 값 검증 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 인증이 필요함 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 역할 또는 당사자 자격이 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 리소스를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    signContract: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 계약 ID
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseContractResponse"];
                };
            };
            /** @description 요청 값 검증 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 인증이 필요함 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 역할 또는 당사자 자격이 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 리소스를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    ackDoorEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 도어 이벤트 ID
                 * @example 123
                 */
                eventId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DoorAckRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseDoorAckResponse"];
                };
            };
            /** @description 요청 값 검증 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 인증이 필요함 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 역할 또는 당사자 자격이 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 리소스를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 지원하지 않는 Content-Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    listFixtures: {
        parameters: {
            query?: {
                /** @description 집기 분류 필터. 생략 시 전체 */
                category?: "HANGER" | "POS" | "SHOWCASE" | "LIGHTING" | "SHELF" | "ETC";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseListFixtureResponse"];
                };
            };
            /** @description 요청 값 검증 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    listReservationRequests: {
        parameters: {
            query?: {
                /** @description 거를 상태. 생략하면 전체 */
                status?: "DRAFT" | "CONTRACT_PENDING" | "CONTRACT_SIGNED" | "PAYMENT_PENDING" | "PAID" | "CANCELLED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseListReservationRequestResponse"];
                };
            };
            /** @description 요청 값 검증 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 인증이 필요함 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    createReservationRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReservationRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseReservationRequestResponse"];
                };
            };
            /** @description 요청 값 검증 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 인증이 필요함 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 역할 또는 당사자 자격이 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 본문이 지목한 공간·집기를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 같은 공간에 기간이 겹치는 결제 완료 예약이 있음 (SPACE_ALREADY_BOOKED) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 지원하지 않는 Content-Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    getReservationRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 예약 요청 ID
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseReservationRequestResponse"];
                };
            };
            /** @description 요청 값 검증 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 인증이 필요함 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 역할 또는 당사자 자격이 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 리소스를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    getContractByReservation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 예약 요청 ID
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseContractResponse"];
                };
            };
            /** @description 요청 값 검증 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 인증이 필요함 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 역할 또는 당사자 자격이 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 리소스를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    createContract: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 예약 요청 ID
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseContractResponse"];
                };
            };
            /** @description 요청 값 검증 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 인증이 필요함 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 역할 또는 당사자 자격이 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 리소스를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    openDoor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 예약 요청 ID
                 * @example 45
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseDoorOpenResponse"];
                };
            };
            /** @description 요청 값 검증 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 인증이 필요함 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 역할 또는 당사자 자격이 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 리소스를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    confirmPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 예약 요청 ID
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentConfirmRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponsePaymentConfirmResponse"];
                };
            };
            /** @description 요청 값 검증 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 인증이 필요함 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 역할 또는 당사자 자격이 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 리소스를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 이미 결제됨 / 기간 겹침 (PAYMENT_ALREADY_COMPLETED, FIXTURE_UNAVAILABLE) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 지원하지 않는 Content-Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 락 획득 실패 — 사용자 잘못이 아니므로 재시도를 안내한다 (LOCK_ACQUISITION_FAILED) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    preparePayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 예약 요청 ID
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponsePaymentPrepareResponse"];
                };
            };
            /** @description 요청 값 검증 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 인증이 필요함 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 역할 또는 당사자 자격이 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 리소스를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    listSettlements: {
        parameters: {
            query: {
                /**
                 * @description 조회할 예약 요청 ID
                 * @example 1
                 */
                reservationId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseListSettlementResponse"];
                };
            };
            /** @description 요청 값 검증 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 인증이 필요함 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 역할 또는 당사자 자격이 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    searchSpaces: {
        parameters: {
            query: {
                /**
                 * @description 중심 위도
                 * @example 37.5445
                 */
                lat: number;
                /**
                 * @description 중심 경도
                 * @example 127.0557
                 */
                lng: number;
                /**
                 * @description 검색 반경(m). 미지정 시 1000
                 * @example 1500
                 */
                radius?: number;
                /**
                 * @description 최소 실면적(㎡)
                 * @example 50
                 */
                minArea?: number;
                /**
                 * @description 일일 대여료 상한(원)
                 * @example 600000
                 */
                maxRent?: number;
                /**
                 * @description 최소 허용 전력(W)
                 * @example 3000
                 */
                minPower?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseListSpaceSummaryResponse"];
                };
            };
            /** @description 요청 값 검증 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    getSpace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 공간 ID
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseSpaceDetailResponse"];
                };
            };
            /** @description 요청 값 검증 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 리소스를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    getFixtureAvailability: {
        parameters: {
            query: {
                /**
                 * @description 사용 시작일
                 * @example 2026-09-01
                 */
                startDate: string;
                /**
                 * @description 사용 종료일
                 * @example 2026-09-14
                 */
                endDate: string;
            };
            header?: never;
            path: {
                /**
                 * @description 대상 공간 ID
                 * @example 1
                 */
                spaceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseListFixtureAvailabilityResponse"];
                };
            };
            /** @description 요청 값 검증 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 인증이 필요함 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 리소스를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
}
