/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그인
         * @description 이메일·비밀번호를 검증하고 Access 토큰을 받는다.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 가입
         * @description 이메일·비밀번호로 가입하고 즉시 Access 토큰을 받는다.
         */
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contracts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 계약 열람
         * @description 조항 전문·서명 시각·무결성 해시를 돌려준다. 분쟁 시 소명 자료 경로다.
         */
        get: operations["detail_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contracts/{id}/sign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 전자 서명
         * @description 로그인 사용자가 해당 계약의 당사자인지 확인한 뒤 서명 시각을 기록한다. 양측이 모두 서명하면 계약은 SIGNED, 예약 요청은 CONTRACT_SIGNED가 된다.
         */
        post: operations["sign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fixtures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 집기 라이브러리 조회
         * @description category를 주면 해당 분류만, 없으면 전체를 돌려준다.
         */
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reservation-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 예약 요청 생성
         * @description 빌더가 만든 도면을 서버에서 재검증하고 견적과 함께 예약 요청을 만든다. 그리드 범위를 벗어나거나 집기가 겹치면 400이다.
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reservation-requests/{id}/contract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 계약서 생성
         * @description 예약 요청 데이터를 표준 템플릿에 바인딩해 조항 전문을 스냅샷으로 저장한다. 예약 요청 상태는 CONTRACT_PENDING으로 전이된다.
         */
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 반경 공실 검색
         * @description 중심 좌표 기준 반경(m) 안의 ACTIVE 공간을 찾는다. 면적·대여료·전력 필터는 모두 선택이다.
         */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spaces/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 상가 상세
         * @description 요약 카드 필드에 빌더 캔버스용 grid 정보를 더해 돌려준다.
         */
        get: operations["detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 에러 상세. 성공 응답에서는 null이다. */
        ApiError: {
            /**
             * @description 에러 코드 상수. 클라이언트는 이 값으로 분기한다
             * @example VALIDATION_FAILED
             * @enum {string}
             */
            code: "VALIDATION_FAILED" | "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "METHOD_NOT_ALLOWED" | "UNSUPPORTED_MEDIA_TYPE" | "INTERNAL_ERROR" | "EMAIL_ALREADY_EXISTS" | "INVALID_CREDENTIALS" | "SPACE_NOT_FOUND" | "FIXTURE_NOT_FOUND" | "RESERVATION_REQUEST_NOT_FOUND" | "LAYOUT_OUT_OF_BOUNDS" | "LAYOUT_OVERLAP" | "FIXTURE_STOCK_EXCEEDED" | "CONTRACT_NOT_FOUND" | "NOT_CONTRACT_PARTY" | "CONTRACT_ALREADY_SIGNED";
            /**
             * @description 사람이 읽는 설명. 분기 조건으로 쓰지 말 것
             * @example email은 필수입니다
             */
            message: string;
        };
        /** @description 실패 응답 봉투. data는 항상 null이고 error에 코드·메시지가 담긴다. */
        ApiErrorResponse: {
            /** @description 실패 시 항상 null */
            data: unknown;
            error: components["schemas"]["ApiError"];
        };
        /** @description 공통 응답 봉투 */
        ApiResponseAuthResponse: {
            /** @description 성공 시 페이로드. 실패 시 null */
            data: components["schemas"]["AuthResponse"] | null;
            /** @description 실패 시 에러 상세. 성공 시 null */
            error: components["schemas"]["ApiError"] | null;
        };
        /** @description 공통 응답 봉투 */
        ApiResponseContractResponse: {
            /** @description 성공 시 페이로드. 실패 시 null */
            data: components["schemas"]["ContractResponse"] | null;
            /** @description 실패 시 에러 상세. 성공 시 null */
            error: components["schemas"]["ApiError"] | null;
        };
        /** @description 공통 응답 봉투 */
        ApiResponseListFixtureResponse: {
            /** @description 성공 시 페이로드. 실패 시 null */
            data: components["schemas"]["FixtureResponse"][] | null;
            /** @description 실패 시 에러 상세. 성공 시 null */
            error: components["schemas"]["ApiError"] | null;
        };
        /** @description 공통 응답 봉투 */
        ApiResponseListSpaceSummaryResponse: {
            /** @description 성공 시 페이로드. 실패 시 null */
            data: components["schemas"]["SpaceSummaryResponse"][] | null;
            /** @description 실패 시 에러 상세. 성공 시 null */
            error: components["schemas"]["ApiError"] | null;
        };
        /** @description 공통 응답 봉투 */
        ApiResponseReservationRequestResponse: {
            /** @description 성공 시 페이로드. 실패 시 null */
            data: components["schemas"]["ReservationRequestResponse"] | null;
            /** @description 실패 시 에러 상세. 성공 시 null */
            error: components["schemas"]["ApiError"] | null;
        };
        /** @description 공통 응답 봉투 */
        ApiResponseSpaceDetailResponse: {
            /** @description 성공 시 페이로드. 실패 시 null */
            data: components["schemas"]["SpaceDetailResponse"] | null;
            /** @description 실패 시 에러 상세. 성공 시 null */
            error: components["schemas"]["ApiError"] | null;
        };
        /** @description 인증 결과 */
        AuthResponse: {
            /** @description JWT Access 토큰. 이후 요청에 Bearer로 싣는다 */
            accessToken: string;
            /** @description 인증된 사용자 정보 */
            user: components["schemas"]["UserSummary"];
        };
        /** @description 계약 조항 */
        ClauseDto: {
            /**
             * @description 조항 전문
             * @example 본 계약은 팝업스토어 단기 운영을 목적으로 한다.
             */
            body: string;
            /**
             * @description 조항 제목
             * @example 제1조 (목적)
             */
            title: string;
        };
        /** @description 계약 */
        ContractResponse: {
            /**
             * Format: date-time
             * @description 브랜드 서명 시각(UTC). 미서명이면 null
             * @example 2026-08-22T05:12:31Z
             */
            brandSignedAt: string | null;
            /** @description 생성 시점의 조항 전문 스냅샷 */
            clauses: components["schemas"]["ClauseDto"][];
            /**
             * @description 조항 전문+타임스탬프의 SHA-256 무결성 해시
             * @example 3f2b7c1d9a4e5f60718293a4b5c6d7e8f90a1b2c3d4e5f60718293a4b5c6d7e8
             */
            contentHash: string;
            /**
             * Format: int64
             * @description 계약 ID
             * @example 1
             */
            id: number;
            /**
             * Format: date-time
             * @description 건물주 서명 시각(UTC). 미서명이면 null
             * @example 2026-08-22T06:40:02Z
             */
            landlordSignedAt: string | null;
            /**
             * Format: int64
             * @description 대상 예약 요청 ID
             * @example 1
             */
            reservationRequestId: number;
            /**
             * @description 계약 상태
             * @enum {string}
             */
            status: "PENDING" | "SIGNED";
            /**
             * @description 템플릿 버전
             * @example v1
             */
            templateVersion: string;
            /**
             * @description 계약 명칭. 일시사용 임대차 요건 보존을 위해 고정된 값이다
             * @example 단기 공간사용 제휴계약
             */
            title: string;
        };
        /** @description 예약 요청 생성 */
        CreateReservationRequest: {
            /**
             * Format: date
             * @description 사용 종료일(yyyy-MM-dd)
             * @example 2026-09-14
             */
            endDate: string;
            /** @description 빌더가 만든 도면 */
            layout: components["schemas"]["LayoutDto"];
            /**
             * Format: int64
             * @description 대상 공간 ID
             * @example 1
             */
            spaceId: number;
            /**
             * Format: date
             * @description 사용 시작일(yyyy-MM-dd)
             * @example 2026-09-01
             */
            startDate: string;
        };
        /** @description 견적 내역 */
        EstimateResponse: {
            /**
             * Format: int32
             * @description 대여 일수
             * @example 14
             */
            days: number;
            /**
             * Format: int64
             * @description 보증금(원). 일시사용 요건상 하향 설계된다
             * @example 630000
             */
            deposit: number;
            /**
             * Format: int64
             * @description 집기 렌털료 합계(원)
             * @example 420000
             */
            fixtureRentalTotal: number;
            /**
             * Format: int64
             * @description 공간 대여료 합계(원)
             * @example 6300000
             */
            spaceRentTotal: number;
            /**
             * Format: int64
             * @description 총 견적(원)
             * @example 7350000
             */
            totalAmount: number;
        };
        /** @description 모듈러 집기 */
        FixtureResponse: {
            /**
             * @description 분류
             * @enum {string}
             */
            category: "HANGER" | "POS" | "SHOWCASE" | "LIGHTING" | "SHELF" | "ETC";
            /**
             * Format: int64
             * @description 일일 렌털료(원)
             * @example 12000
             */
            dailyRentalFee: number;
            /**
             * Format: int32
             * @description 세로 규격(mm)
             * @example 500
             */
            depthMm: number;
            /**
             * Format: int64
             * @description 집기 ID
             * @example 1
             */
            id: number;
            /**
             * @description 집기 이름
             * @example 스탠드 행거 1200
             */
            name: string;
            /**
             * Format: int32
             * @description 소비 전력(W). 비전기 집기는 0
             * @example 0
             */
            powerWatt: number;
            /**
             * Format: int32
             * @description 총 재고 수량
             * @example 40
             */
            stockQty: number;
            /**
             * Format: int32
             * @description 가로 규격(mm)
             * @example 1200
             */
            widthMm: number;
        };
        /** @description 2D 도면 레이아웃 */
        LayoutDto: {
            /**
             * Format: int32
             * @description 그리드 한 칸의 실제 크기(mm)
             * @example 500
             */
            cellSizeMm: number;
            /**
             * Format: int32
             * @description 그리드 가로 칸 수
             * @example 20
             */
            gridCols: number;
            /**
             * Format: int32
             * @description 그리드 세로 칸 수
             * @example 12
             */
            gridRows: number;
            /** @description 배치된 집기 목록. 빈 배열도 허용한다 */
            items: components["schemas"]["LayoutItemDto"][];
        };
        /** @description 배치된 집기 */
        LayoutItemDto: {
            /**
             * Format: int32
             * @description 좌상단 기준 열 좌표(0-base)
             * @example 4
             */
            col: number;
            /**
             * Format: int64
             * @description 집기 ID
             * @example 3
             */
            fixtureId: number;
            /**
             * Format: int32
             * @description 회전각. 0 | 90 | 180 | 270 중 하나여야 한다
             * @example 90
             */
            rotation: number;
            /**
             * Format: int32
             * @description 좌상단 기준 행 좌표(0-base)
             * @example 2
             */
            row: number;
        };
        /** @description 위경도 좌표(WGS84) */
        LocationDto: {
            /**
             * Format: double
             * @description 위도
             * @example 37.5445
             */
            lat: number;
            /**
             * Format: double
             * @description 경도
             * @example 127.0557
             */
            lng: number;
        };
        /** @description 로그인 요청 */
        LoginRequest: {
            /**
             * @description 이메일(로그인 ID)
             * @example brand@popupready.com
             */
            email: string;
            /**
             * @description 비밀번호
             * @example password123
             */
            password: string;
        };
        /** @description 예약 요청 */
        ReservationRequestResponse: {
            /**
             * Format: int64
             * @description 요청한 브랜드 사용자 ID
             * @example 1
             */
            brandUserId: number;
            /**
             * Format: date
             * @description 사용 종료일
             * @example 2026-09-14
             */
            endDate: string;
            /** @description 견적 내역 */
            estimate: components["schemas"]["EstimateResponse"];
            /**
             * Format: int64
             * @description 예약 요청 ID
             * @example 1
             */
            id: number;
            /** @description 서버가 재검증한 도면. 요청한 내용이 그대로 되돌아온다 */
            layout: components["schemas"]["LayoutDto"];
            /**
             * Format: int64
             * @description 대상 공간 ID
             * @example 1
             */
            spaceId: number;
            /**
             * Format: date
             * @description 사용 시작일
             * @example 2026-09-01
             */
            startDate: string;
            /**
             * @description 예약 요청 상태
             * @enum {string}
             */
            status: "DRAFT" | "CONTRACT_PENDING" | "CONTRACT_SIGNED";
        };
        /** @description 가입 요청 */
        SignupRequest: {
            /**
             * Format: email
             * @description 이메일(로그인 ID)
             * @example brand@popupready.com
             */
            email: string;
            /**
             * @description 표시 이름
             * @example 김브랜드
             */
            name: string;
            /**
             * @description 비밀번호(8자 이상)
             * @example password123
             */
            password: string;
            /**
             * @description 역할
             * @enum {string}
             */
            role: "BRAND" | "LANDLORD" | "VENDOR" | "ADMIN";
        };
        /** @description 공간 상세(빌더 진입용) */
        SpaceDetailResponse: {
            /**
             * @description 주소
             * @example 서울 성동구 연무장길 45
             */
            address: string;
            /**
             * Format: int32
             * @description 그리드 한 칸의 실제 크기(mm)
             * @example 500
             */
            cellSizeMm: number;
            /**
             * Format: int64
             * @description 일일 대여료(원)
             * @example 450000
             */
            dailyRent: number;
            /**
             * @description 보증금 비율. 일시사용 요건상 하향 설계된다
             * @example 0.1
             */
            depositRate: number;
            /**
             * Format: double
             * @description 실면적(㎡)
             * @example 82.5
             */
            floorAreaM2: number;
            /**
             * Format: int32
             * @description 도면 그리드 가로 칸 수
             * @example 20
             */
            gridCols: number;
            /**
             * Format: int32
             * @description 도면 그리드 세로 칸 수
             * @example 12
             */
            gridRows: number;
            /**
             * Format: int64
             * @description 공간 ID
             * @example 1
             */
            id: number;
            /** @description 위치 좌표 */
            location: components["schemas"]["LocationDto"];
            /**
             * Format: int32
             * @description 허용 전력(W). 배치한 집기 소비전력 합이 이 값을 넘으면 결제가 차단된다
             * @example 5000
             */
            maxPowerWatt: number;
            /**
             * @description 공간 이름
             * @example 성수 연무장길 팝업 1층
             */
            name: string;
            /**
             * @description 공간 상태
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE";
        };
        /** @description 공간 요약(지도 마커·요약 카드용) */
        SpaceSummaryResponse: {
            /**
             * @description 주소
             * @example 서울 성동구 연무장길 45
             */
            address: string;
            /**
             * Format: int64
             * @description 일일 대여료(원)
             * @example 450000
             */
            dailyRent: number;
            /**
             * Format: double
             * @description 실면적(㎡)
             * @example 82.5
             */
            floorAreaM2: number;
            /**
             * Format: int64
             * @description 공간 ID
             * @example 1
             */
            id: number;
            /** @description 위치 좌표 */
            location: components["schemas"]["LocationDto"];
            /**
             * Format: int32
             * @description 허용 전력(W)
             * @example 5000
             */
            maxPowerWatt: number;
            /**
             * @description 공간 이름
             * @example 성수 연무장길 팝업 1층
             */
            name: string;
        };
        /** @description 로그인한 사용자 요약 */
        UserSummary: {
            /**
             * @description 이메일(로그인 ID)
             * @example brand@popupready.com
             */
            email: string;
            /**
             * Format: int64
             * @description 사용자 ID
             * @example 1
             */
            id: number;
            /**
             * @description 표시 이름
             * @example 김브랜드
             */
            name: string;
            /**
             * @description 역할
             * @enum {string}
             */
            role: "BRAND" | "LANDLORD" | "VENDOR" | "ADMIN";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseAuthResponse"];
                };
            };
            /** @description 요청 값 검증 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 지원하지 않는 Content-Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseAuthResponse"];
                };
            };
            /** @description 요청 값 검증 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 지원하지 않는 Content-Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    detail_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 계약 ID
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseContractResponse"];
                };
            };
            /** @description 요청 값 검증 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 리소스를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    sign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 계약 ID
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseContractResponse"];
                };
            };
            /** @description 요청 값 검증 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 리소스를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                /** @description 집기 분류 필터. 생략 시 전체 */
                category?: "HANGER" | "POS" | "SHOWCASE" | "LIGHTING" | "SHELF" | "ETC";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseListFixtureResponse"];
                };
            };
            /** @description 요청 값 검증 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReservationRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseReservationRequestResponse"];
                };
            };
            /** @description 요청 값 검증 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 지원하지 않는 Content-Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 예약 요청 ID
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseContractResponse"];
                };
            };
            /** @description 요청 값 검증 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 리소스를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                /**
                 * @description 중심 위도
                 * @example 37.5445
                 */
                lat: number;
                /**
                 * @description 중심 경도
                 * @example 127.0557
                 */
                lng: number;
                /**
                 * @description 검색 반경(m). 미지정 시 1000
                 * @example 1500
                 */
                radius?: number;
                /**
                 * @description 최소 실면적(㎡)
                 * @example 50
                 */
                minArea?: number;
                /**
                 * @description 일일 대여료 상한(원)
                 * @example 600000
                 */
                maxRent?: number;
                /**
                 * @description 최소 허용 전력(W)
                 * @example 3000
                 */
                minPower?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseListSpaceSummaryResponse"];
                };
            };
            /** @description 요청 값 검증 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 공간 ID
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseSpaceDetailResponse"];
                };
            };
            /** @description 요청 값 검증 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 리소스를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
}
